### ISSUE TITLE
Instead of port...use IronPython?

### ISSUE THREAD

**Issue by tig** [akatakritos/PygmentSharp#13]
I'm working on something where I need Pygments from a c# app. 

I was going down the path of using IronPython to host the Python version of pygments, when I found this.

I'm curious if you considered doing that back when you created this. I have not looked deeply at the Pygments source and I'm not very well versed in Python. I need a bunch of stuff you have not ported yet (e.g. the terminal formatters and full support for styles). 

Any insight or opinions?

**Comment by akatakritos** [comment]
Sorry, I don't have any experience with  IronPython, and I didn't really look into it. My main goal was to port just enough stuff to write my own static generator for my blog, but eventually gave up on that too!

There looks to be a few other highlighters on nuget -- would any of those work? Or were you looking for something closer to pygments?
